"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var pak_js_1 = require("./pak.js");
var ind_js_1 = require("./ind.js");
var ind_js_2 = require("./ind.js");
console.log("Population of pakistan is ".concat(pak_js_1.default));
console.log("Population of India is ".concat(ind_js_1.default));
console.log("multiply of India is ".concat((0, pak_js_1.multiply)(5, 5)));
console.log("divide of India is ".concat((0, ind_js_2.divide)(2005, 5)));
console.log("Cities of pakistan are ".concat(pak_js_1.cities));
console.log("Cities of India are ".concat(ind_js_1.cities));
